[build-system]
requires = [
    "poetry==1.1.6",
]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "advanced_flwr_pytorch"
version = "0.1.0"
description = "Advanced Flower/PyTorch Example"
authors = ["The Flower Authors <enquiries@flower.dev>"]

[tool.poetry.dependencies]
python = "^3.6.2"
flwr = "^0.16.0"  # For development: { path = "../../", develop = true }
torch = "^1.9.0"
torchvision = "^0.10.0"
