[build-system]
requires = [
    "poetry==1.1.4",
]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "single_process_tensorflow"
version = "0.1.0"
description = "Single-Process Federated Learning Quickstart with Flower"
authors = ["The Flower Authors <enquiries@flower.dev>"]

[tool.poetry.dependencies]
python = "^3.6.1"
flwr = { path = "../../", develop = true }
tensorflow-cpu = "2.4.0"
